# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from rociadb_sdk._pb.upstream.v1 import upstream_pb2 as upstream_dot_v1_dot_upstream__pb2

GRPC_GENERATED_VERSION = "1.83.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in upstream/v1/upstream_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DocumentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutDoc = channel.unary_unary(
            "/rocia.v1.DocumentService/PutDoc",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.PutDocRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.GetDoc = channel.unary_unary(
            "/rocia.v1.DocumentService/GetDoc",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.GetDocRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.GetDocResponse.FromString,
            _registered_method=True,
        )
        self.DeleteDoc = channel.unary_unary(
            "/rocia.v1.DocumentService/DeleteDoc",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.DeleteDocRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.FindByField = channel.unary_unary(
            "/rocia.v1.DocumentService/FindByField",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.FindByFieldRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.FindByFieldResponse.FromString,
            _registered_method=True,
        )
        self.ListDoc = channel.unary_unary(
            "/rocia.v1.DocumentService/ListDoc",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.ListDocRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.ListDocResponse.FromString,
            _registered_method=True,
        )
        self.QueryDoc = channel.unary_unary(
            "/rocia.v1.DocumentService/QueryDoc",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.QueryDocRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.QueryDocResponse.FromString,
            _registered_method=True,
        )
        self.ListCollections = channel.unary_unary(
            "/rocia.v1.DocumentService/ListCollections",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.ListCollectionsRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.ListCollectionsResponse.FromString,
            _registered_method=True,
        )


class DocumentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PutDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FindByField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "PutDoc": grpc.unary_unary_rpc_method_handler(
            servicer.PutDoc,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.PutDocRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "GetDoc": grpc.unary_unary_rpc_method_handler(
            servicer.GetDoc,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.GetDocRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.GetDocResponse.SerializeToString,
        ),
        "DeleteDoc": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteDoc,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.DeleteDocRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "FindByField": grpc.unary_unary_rpc_method_handler(
            servicer.FindByField,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.FindByFieldRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.FindByFieldResponse.SerializeToString,
        ),
        "ListDoc": grpc.unary_unary_rpc_method_handler(
            servicer.ListDoc,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.ListDocRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.ListDocResponse.SerializeToString,
        ),
        "QueryDoc": grpc.unary_unary_rpc_method_handler(
            servicer.QueryDoc,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.QueryDocRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.QueryDocResponse.SerializeToString,
        ),
        "ListCollections": grpc.unary_unary_rpc_method_handler(
            servicer.ListCollections,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.ListCollectionsRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.ListCollectionsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rocia.v1.DocumentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rocia.v1.DocumentService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class DocumentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutDoc(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.DocumentService/PutDoc",
            upstream_dot_v1_dot_upstream__pb2.PutDocRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDoc(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.DocumentService/GetDoc",
            upstream_dot_v1_dot_upstream__pb2.GetDocRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.GetDocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteDoc(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.DocumentService/DeleteDoc",
            upstream_dot_v1_dot_upstream__pb2.DeleteDocRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FindByField(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.DocumentService/FindByField",
            upstream_dot_v1_dot_upstream__pb2.FindByFieldRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.FindByFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListDoc(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.DocumentService/ListDoc",
            upstream_dot_v1_dot_upstream__pb2.ListDocRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.ListDocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QueryDoc(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.DocumentService/QueryDoc",
            upstream_dot_v1_dot_upstream__pb2.QueryDocRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.QueryDocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListCollections(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.DocumentService/ListCollections",
            upstream_dot_v1_dot_upstream__pb2.ListCollectionsRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class GraphServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutNode = channel.unary_unary(
            "/rocia.v1.GraphService/PutNode",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.PutNodeRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.GetNode = channel.unary_unary(
            "/rocia.v1.GraphService/GetNode",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.GetNodeRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.GetNodeResponse.FromString,
            _registered_method=True,
        )
        self.AddEdge = channel.unary_unary(
            "/rocia.v1.GraphService/AddEdge",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.AddEdgeRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.DeleteEdge = channel.unary_unary(
            "/rocia.v1.GraphService/DeleteEdge",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.DeleteEdgeRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.NeighborsOut = channel.unary_unary(
            "/rocia.v1.GraphService/NeighborsOut",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.NeighborsOutRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.NeighborsOutResponse.FromString,
            _registered_method=True,
        )
        self.NeighborsIn = channel.unary_unary(
            "/rocia.v1.GraphService/NeighborsIn",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.NeighborsInRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.NeighborsInResponse.FromString,
            _registered_method=True,
        )
        self.ListGraphs = channel.unary_unary(
            "/rocia.v1.GraphService/ListGraphs",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.ListGraphsRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.ListGraphsResponse.FromString,
            _registered_method=True,
        )
        self.ListNodes = channel.unary_unary(
            "/rocia.v1.GraphService/ListNodes",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.ListNodesRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.ListNodesResponse.FromString,
            _registered_method=True,
        )


class GraphServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PutNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def NeighborsOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def NeighborsIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListGraphs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "PutNode": grpc.unary_unary_rpc_method_handler(
            servicer.PutNode,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.PutNodeRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "GetNode": grpc.unary_unary_rpc_method_handler(
            servicer.GetNode,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.GetNodeRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.GetNodeResponse.SerializeToString,
        ),
        "AddEdge": grpc.unary_unary_rpc_method_handler(
            servicer.AddEdge,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.AddEdgeRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "DeleteEdge": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteEdge,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.DeleteEdgeRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "NeighborsOut": grpc.unary_unary_rpc_method_handler(
            servicer.NeighborsOut,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.NeighborsOutRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.NeighborsOutResponse.SerializeToString,
        ),
        "NeighborsIn": grpc.unary_unary_rpc_method_handler(
            servicer.NeighborsIn,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.NeighborsInRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.NeighborsInResponse.SerializeToString,
        ),
        "ListGraphs": grpc.unary_unary_rpc_method_handler(
            servicer.ListGraphs,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.ListGraphsRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.ListGraphsResponse.SerializeToString,
        ),
        "ListNodes": grpc.unary_unary_rpc_method_handler(
            servicer.ListNodes,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.ListNodesRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.ListNodesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rocia.v1.GraphService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rocia.v1.GraphService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GraphService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.GraphService/PutNode",
            upstream_dot_v1_dot_upstream__pb2.PutNodeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.GraphService/GetNode",
            upstream_dot_v1_dot_upstream__pb2.GetNodeRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddEdge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.GraphService/AddEdge",
            upstream_dot_v1_dot_upstream__pb2.AddEdgeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteEdge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.GraphService/DeleteEdge",
            upstream_dot_v1_dot_upstream__pb2.DeleteEdgeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def NeighborsOut(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.GraphService/NeighborsOut",
            upstream_dot_v1_dot_upstream__pb2.NeighborsOutRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.NeighborsOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def NeighborsIn(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.GraphService/NeighborsIn",
            upstream_dot_v1_dot_upstream__pb2.NeighborsInRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.NeighborsInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListGraphs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.GraphService/ListGraphs",
            upstream_dot_v1_dot_upstream__pb2.ListGraphsRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.ListGraphsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListNodes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.GraphService/ListNodes",
            upstream_dot_v1_dot_upstream__pb2.ListNodesRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class FileServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
            "/rocia.v1.FileService/Upload",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.UploadRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.Download = channel.unary_stream(
            "/rocia.v1.FileService/Download",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.DownloadRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.DownloadResponse.FromString,
            _registered_method=True,
        )
        self.Stat = channel.unary_unary(
            "/rocia.v1.FileService/Stat",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.StatRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.StatResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/rocia.v1.FileService/Delete",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.DeleteRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.ListBuckets = channel.unary_unary(
            "/rocia.v1.FileService/ListBuckets",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.ListBucketsRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.ListBucketsResponse.FromString,
            _registered_method=True,
        )
        self.ListFiles = channel.unary_unary(
            "/rocia.v1.FileService/ListFiles",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.ListFilesRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.ListFilesResponse.FromString,
            _registered_method=True,
        )


class FileServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Upload": grpc.stream_unary_rpc_method_handler(
            servicer.Upload,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.UploadRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "Download": grpc.unary_stream_rpc_method_handler(
            servicer.Download,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.DownloadRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.DownloadResponse.SerializeToString,
        ),
        "Stat": grpc.unary_unary_rpc_method_handler(
            servicer.Stat,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.StatRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.StatResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.DeleteRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "ListBuckets": grpc.unary_unary_rpc_method_handler(
            servicer.ListBuckets,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.ListBucketsRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.ListBucketsResponse.SerializeToString,
        ),
        "ListFiles": grpc.unary_unary_rpc_method_handler(
            servicer.ListFiles,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.ListFilesRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.ListFilesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rocia.v1.FileService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rocia.v1.FileService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class FileService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upload(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/rocia.v1.FileService/Upload",
            upstream_dot_v1_dot_upstream__pb2.UploadRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Download(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/rocia.v1.FileService/Download",
            upstream_dot_v1_dot_upstream__pb2.DownloadRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Stat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.FileService/Stat",
            upstream_dot_v1_dot_upstream__pb2.StatRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.FileService/Delete",
            upstream_dot_v1_dot_upstream__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListBuckets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.FileService/ListBuckets",
            upstream_dot_v1_dot_upstream__pb2.ListBucketsRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.ListBucketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListFiles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.FileService/ListFiles",
            upstream_dot_v1_dot_upstream__pb2.ListFilesRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class TenantServiceStub:
    """Opérations transverses aux tenants.

    Séparé des trois services de modèle parce que rien ici n'est scopé à un
    tenant : ListTenants énumère l'ensemble du déploiement. Ce découpage permet
    de lui appliquer une politique d'autorisation propre le jour où il en faudra
    une, sans toucher aux services de données.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTenants = channel.unary_unary(
            "/rocia.v1.TenantService/ListTenants",
            request_serializer=upstream_dot_v1_dot_upstream__pb2.ListTenantsRequest.SerializeToString,
            response_deserializer=upstream_dot_v1_dot_upstream__pb2.ListTenantsResponse.FromString,
            _registered_method=True,
        )


class TenantServiceServicer:
    """Opérations transverses aux tenants.

    Séparé des trois services de modèle parce que rien ici n'est scopé à un
    tenant : ListTenants énumère l'ensemble du déploiement. Ce découpage permet
    de lui appliquer une politique d'autorisation propre le jour où il en faudra
    une, sans toucher aux services de données.
    """

    def ListTenants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TenantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListTenants": grpc.unary_unary_rpc_method_handler(
            servicer.ListTenants,
            request_deserializer=upstream_dot_v1_dot_upstream__pb2.ListTenantsRequest.FromString,
            response_serializer=upstream_dot_v1_dot_upstream__pb2.ListTenantsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rocia.v1.TenantService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rocia.v1.TenantService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class TenantService:
    """Opérations transverses aux tenants.

    Séparé des trois services de modèle parce que rien ici n'est scopé à un
    tenant : ListTenants énumère l'ensemble du déploiement. Ce découpage permet
    de lui appliquer une politique d'autorisation propre le jour où il en faudra
    une, sans toucher aux services de données.
    """

    @staticmethod
    def ListTenants(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rocia.v1.TenantService/ListTenants",
            upstream_dot_v1_dot_upstream__pb2.ListTenantsRequest.SerializeToString,
            upstream_dot_v1_dot_upstream__pb2.ListTenantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
